In [36]:
import pandas as pd

df = pd.read_csv("../data/cleaned_train_data.csv")

df.head(10)

categorical_cols = ['Time_of_Day', 'Day_of_Week', 'Traffic_Conditions', 'Weather']

df_encoded = pd.get_dummies(df, columns=categorical_cols, drop_first=True)

df.head(20)

,Trip_Distance_km,Time_of_Day,Day_of_Week,Passenger_Count,Traffic_Conditions,Weather,Base_Fare,Per_Km_Rate,Per_Minute_Rate,Trip_Duration_Minutes,Trip_Price
0,19.35,Morning,Weekday,3.0,Low,Clear,3.56,0.80,0.32,53.82,36.2624
1,36.87,Evening,Weekend,1.0,High,Clear,2.70,1.21,0.15,37.27,52.9032
2,8.64,Afternoon,Weekend,2.0,Medium,Clear,2.55,1.71,0.48,89.33,60.2028
3,41.79,Night,Weekend,3.0,High,Clear,4.60,1.77,0.11,86.95,88.1328
4,9.91,Evening,Weekday,2.0,High,Clear,2.32,1.26,0.34,41.72,28.9914
5,9.99,Night,Weekday,4.0,High,Clear,4.33,0.85,0.43,34.00,27.4415
6,15.91,Morning,Weekday,4.0,Low,Clear,4.42,1.77,0.21,114.93,56.7160
7,26.71,Afternoon,Weekend,4.0,Low,Rain,4.30,1.59,0.20,111.18,69.0049
8,30.98,Afternoon,Weekend,1.0,Low,Rain,4.50,0.84,0.25,57.02,44.7782
9,18.95,Night,Weekday,1.0,Low,Clear,3.38,0.78,0.39,54.04,39.2366
10,3.28,Evening,Weekday,2.0,Medium,Clear,2.88,1.76,0.20,78.04,24.2608
11,30.77,Morning,Weekday,1.0,Low,Clear,3.64,1.33,0.13,109.60,58.8121
12,9.36,Afternoon,Weekday,1.0,Medium,Clear,2.40,1.85,0.15,7.07,20.7765
13,48.32,Morning,Weekday,2.0,Low,Clear,2.49,0.61,0.44,67.25,61.5552
14,40.61,Afternoon,Weekday,1.0,Low,Clear,2.31,0.88,0.38,42.25,54.1018
15,5.79,Evening,Weekday,4.0,Low,Clear,4.63,1.83,0.24,107.07,40.9225
16,6.98,Afternoon,Weekend,2.0,Low,Clear,2.32,0.78,0.18,72.37,20.7910
17,25.26,Evening,Weekday,2.0,High,Clear,3.95,1.71,0.12,82.53,57.0482
18,2.69,Afternoon,Weekday,4.0,Low,Clear,4.60,1.95,0.34,97.49,42.9921
19,33.46,Afternoon,Weekend,2.0,Low,Rain,2.23,0.63,0.12,64.07,30.9982

In [37]:
df_encoded

,Trip_Distance_km,Passenger_Count,Base_Fare,Per_Km_Rate,Per_Minute_Rate,Trip_Duration_Minutes,Trip_Price,Time_of_Day_Evening,Time_of_Day_Morning,Time_of_Day_Night,Day_of_Week_Weekend,Traffic_Conditions_Low,Traffic_Conditions_Medium,Weather_Rain,Weather_Snow
0,19.35,3.0,3.56,0.80,0.32,53.82,36.2624,False,True,False,False,True,False,False,False
1,36.87,1.0,2.70,1.21,0.15,37.27,52.9032,True,False,False,True,False,False,False,False
2,8.64,2.0,2.55,1.71,0.48,89.33,60.2028,False,False,False,True,False,True,False,False
3,41.79,3.0,4.60,1.77,0.11,86.95,88.1328,False,False,True,True,False,False,False,False
4,9.91,2.0,2.32,1.26,0.34,41.72,28.9914,True,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
540,40.17,3.0,3.81,0.66,0.42,62.66,56.6394,True,False,False,False,True,False,False,False
541,14.34,1.0,3.23,1.01,0.29,45.07,30.7837,False,False,False,False,False,True,False,False
542,18.69,3.0,4.90,1.79,0.17,79.41,51.8548,True,False,False,False,False,True,False,False
543,5.49,4.0,2.39,0.62,0.49,58.39,34.4049,False,False,False,True,False,True,False,False
544,47.56,1.0,2.67,0.82,0.17,114.94,61.2090,False,True,False,False,True,False,False,False

In [38]:
df.describe().T

,count,mean,std,min,25%,50%,75%,max
Trip_Distance_km,545.0,25.174771,14.262331,1.2700,12.860,25.4200,37.6300,49.9900
Passenger_Count,545.0,2.532110,1.107866,1.0000,2.000,3.0000,4.0000,4.0000
Base_Fare,545.0,3.511284,0.867880,2.0100,2.730,3.5400,4.2600,5.0000
Per_Km_Rate,545.0,1.212716,0.426728,0.5000,0.840,1.1900,1.5600,2.0000
Per_Minute_Rate,545.0,0.288239,0.115121,0.1000,0.190,0.2800,0.3900,0.5000
Trip_Duration_Minutes,545.0,61.595927,32.279141,5.0100,36.330,61.1600,88.4400,119.8400
Trip_Price,545.0,51.450541,23.584796,6.1269,33.183,48.7802,66.5363,118.0321

In [39]:
from sklearn.model_selection import train_test_split

x = df_encoded.drop('Trip_Price', axis=1) # Använd den nya DataFrame
y = df_encoded['Trip_Price']
x.head(15)

,Trip_Distance_km,Passenger_Count,Base_Fare,Per_Km_Rate,Per_Minute_Rate,Trip_Duration_Minutes,Time_of_Day_Evening,Time_of_Day_Morning,Time_of_Day_Night,Day_of_Week_Weekend,Traffic_Conditions_Low,Traffic_Conditions_Medium,Weather_Rain,Weather_Snow
0,19.35,3.0,3.56,0.80,0.32,53.82,False,True,False,False,True,False,False,False
1,36.87,1.0,2.70,1.21,0.15,37.27,True,False,False,True,False,False,False,False
2,8.64,2.0,2.55,1.71,0.48,89.33,False,False,False,True,False,True,False,False
3,41.79,3.0,4.60,1.77,0.11,86.95,False,False,True,True,False,False,False,False
4,9.91,2.0,2.32,1.26,0.34,41.72,True,False,False,False,False,False,False,False
5,9.99,4.0,4.33,0.85,0.43,34.00,False,False,True,False,False,False,False,False
6,15.91,4.0,4.42,1.77,0.21,114.93,False,True,False,False,True,False,False,False
7,26.71,4.0,4.30,1.59,0.20,111.18,False,False,False,True,True,False,True,False
8,30.98,1.0,4.50,0.84,0.25,57.02,False,False,False,True,True,False,True,False
9,18.95,1.0,3.38,0.78,0.39,54.04,False,False,True,False,True,False,False,False
10,3.28,2.0,2.88,1.76,0.20,78.04,True,False,False,False,False,True,False,False
11,30.77,1.0,3.64,1.33,0.13,109.60,False,True,False,False,True,False,False,False
12,9.36,1.0,2.40,1.85,0.15,7.07,False,False,False,False,False,True,False,False
13,48.32,2.0,2.49,0.61,0.44,67.25,False,True,False,False,True,False,False,False
14,40.61,1.0,2.31,0.88,0.38,42.25,False,False,False,False,True,False,False,False

In [40]:
X_train, X_test, y_train, y_test = train_test_split(
    x, y, test_size=0.33, random_state=42)
X_train.shape, X_test.shape

((365, 14), (180, 14))

In [65]:
from sklearn.ensemble import RandomForestRegressor

model = RandomForestRegressor()
model.fit(X_train, y_train)

y_pred = model.predict(X_test)

print(y_test, y_pred)

316    32.7178
77     36.4958
360    20.3509
90     62.8950
493    26.1975
        ...
17     57.0482
402    31.4354
66     53.0560
238    57.4261
272    45.2346
Name: Trip_Price, Length: 180, dtype: float64 [ 28.818331  39.351094  20.954667  66.792328  29.246269  43.185026
  52.293201  33.395215  18.692136  92.640045  44.466656  44.366987
  57.772839  27.127498  58.042163  69.420516  23.753213  34.417332
  29.119676  21.992774  68.889363  44.047384  45.140493  34.817587
  95.39987   55.019788  34.854751  68.539956  26.137363  79.56347
  73.857212  37.904115  17.344848  36.702045 101.307558  51.427906
  91.020279  25.482769  29.527365  42.606017  73.821724  33.085087
  31.582721  36.348184  76.064619  43.80034   46.661547  51.667034
  81.870736  55.993329  72.743346  79.0545    39.36514   65.254605
  74.029913  35.078947  40.92149   40.932674  32.600562  45.030965
  59.3635    70.746025  96.591753  37.084433  40.763171  40.14906
  27.207054  60.728819  62.912859  34.709352  44.019369  38.4258
  57.518105  41.193643  48.073792  66.83004   73.131523  35.972595
  47.088918  55.701923  52.087419  41.261722  55.219096  92.928976
  55.002116  77.451921  39.735777  50.291217  37.624583  62.766543
  76.222716  22.927819  69.548449  27.58863   17.003934  10.583424
  65.734956  40.74415   25.047434  29.304961  17.691417  45.796723
  27.699967  94.737733  40.719907  73.659698  88.409448  32.615192
  60.430754  34.282592  62.294382  37.150596  32.098963  39.492708
  41.922161  54.100516  23.626849  16.669864  57.91924   86.922257
  36.683332  68.164224  65.141014  53.774413  11.599127  30.29346
  79.649153  61.070125  36.413851  41.188924  39.674095  63.930997
  59.711922  39.642255  63.328473  45.471722  47.364645  77.382894
  40.363232  91.018071  98.6924   103.971916  61.848073  61.36134
  43.923422  27.520058  34.246216  37.556386  75.100947  34.64738
  66.881679  45.269285  28.267429  59.032866  16.659144  38.072121
  64.818732  32.624431  13.413205  43.225294  68.410419  49.399327
  82.731754  61.504634  28.76153   24.926197  50.946377  57.436086
  64.881878  55.543793  56.539024 107.81981   42.402232 100.045168
  53.103391  66.618004  40.289652  49.604069  58.898523  49.086007]

Beräknar MAE. MAE mäter den genomsnittliga storleken på felet i dina förutsägelser, utan att bry sig om riktningen (om gissningen var för hög eller för låg).

In [66]:
from sklearn.metrics import mean_absolute_error

mae = mean_absolute_error(y_test, y_pred)

print(f"Mean Absolute Error (MAE): {mae:.2f}")

Mean Absolute Error (MAE): 4.58

Beräknar RMSE = Root Mean Squared Error (RMSE). RMSE ger större vikt åt stora fel (stora outliers) än vad MAE gör, vilket är bra om du vill straffa modellen hårt för väldigt dåliga gissningar.

In [67]:
from sklearn.metrics import mean_squared_error
import numpy as np

rmse = np.sqrt(mean_squared_error(y_test, y_pred))
print(f"Root Mean Squared Error (RMSE): {rmse:.2f}")

Root Mean Squared Error (RMSE): 5.98

## Linjär Regression model

In [57]:
from sklearn.linear_model import LinearRegression

lr_model = LinearRegression()
lr_model.fit(X_train, y_train)
lr_y_pred = lr_model.predict(X_test)

lr_mae = mean_absolute_error(y_test, lr_y_pred)
lr_rmse = np.sqrt(mean_squared_error(y_test, lr_y_pred))



print("Resultat: Linjär Regression")
print(f"Mean Absolute Error (MAE): {lr_mae:.2f}")
print(f"Root Mean Squared Error (RMSE): {lr_rmse:.2f}")

Resultat: Linjär Regression
Mean Absolute Error (MAE): 5.59
Root Mean Squared Error (RMSE): 7.11

## GradientBoostingRegressor model

In [71]:
from sklearn.ensemble import GradientBoostingRegressor


gbr_model = GradientBoostingRegressor(n_estimators=100, learning_rate=0.1, max_depth=3, random_state=42)
gbr_model.fit(X_train, y_train)

gbr_y_pred = gbr_model.predict(X_test)

gbr_mae = mean_absolute_error(y_test, gbr_y_pred)
gbr_rmse = np.sqrt(mean_squared_error(y_test, gbr_y_pred))

print("Resultat: Gradient Boosting Regression")
print(f"Mean Absolute Error (MAE): {gbr_mae:.2f}")
print(f"Root Mean Squared Error (RMSE): {gbr_rmse:.2f}")

Resultat: Gradient Boosting Regression
Mean Absolute Error (MAE): 3.26
Root Mean Squared Error (RMSE): 4.51

## GradientBoostingRegressor är vinnaren av modellerna 

- Träna nya modellen med all data
- Exportera modellen med joblib

In [ ]:
import joblib

# parametrarna hjälper modellen få bättre resultat och ger den bättre prestanda
gbr_model_final = GradientBoostingRegressor(
    n_estimators=100,  # Antal träd att bygga (standard är 100).
    learning_rate=0.1, # Hur snabbt modellen lär sig från sina fel (standard är 0.1).
    max_depth=3, # Hur djupt varje individuellt träd får bli (begränsar komplexiteten och förhindrar överanpassning, standard är 3).
    random_state=42 # Ger dig ett reproducerbart resultat varje gång du kör koden.
    )

gbr_model_final.fit(x, y) 

MODEL_PATH = "../models/gbr_final_model.joblib" 
joblib.dump(gbr_model_final, MODEL_PATH)

FileNotFoundError: [Errno 2] No such file or directory: '../taxipred/models/gbr_final_model.joblib'